//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23049999_Sewanta_Luitel
{


    public partial class _Default
    {
        protected global::System.Web.UI.WebControls.Label lblTotalUsers;

        protected global::System.Web.UI.WebControls.Label lblTotalMovies;

        protected global::System.Web.UI.WebControls.Label lblTotalShows;

        protected global::System.Web.UI.WebControls.Label lblTotalTicketsSold;

        protected global::System.Web.UI.WebControls.TextBox txtName;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.TextBox txtAddress;

        protected global::System.Web.UI.WebControls.Button btnAdd;

        protected global::System.Web.UI.WebControls.Button btnUpdate;

        protected global::System.Web.UI.WebControls.Button btnDelete;

        protected global::System.Web.UI.WebControls.GridView GridViewUsers;

        protected global::System.Web.UI.WebControls.TextBox txtMovieName;

        protected global::System.Web.UI.WebControls.TextBox txtReleaseDate;

        protected global::System.Web.UI.WebControls.Button btnAddMovie;

        protected global::System.Web.UI.WebControls.Button btnUpdateMovie;

        protected global::System.Web.UI.WebControls.Button btnDeleteMovie;

        protected global::System.Web.UI.WebControls.GridView GridViewMovies;

        protected global::System.Web.UI.WebControls.TextBox txtTheaterName;

        protected global::System.Web.UI.WebControls.TextBox txtTheaterCity;

        protected global::System.Web.UI.WebControls.Button btnAddTheater;

        protected global::System.Web.UI.WebControls.DropDownList ddlTheaterId;

        protected global::System.Web.UI.WebControls.TextBox txtHallNumber;

        protected global::System.Web.UI.WebControls.TextBox txtHallCapacity;

        protected global::System.Web.UI.WebControls.Button btnAddHall;

        protected global::System.Web.UI.WebControls.Button btnUpdateHall;

        protected global::System.Web.UI.WebControls.Button btnDeleteHall;

        protected global::System.Web.UI.WebControls.GridView GridViewTheaters;

        protected global::System.Web.UI.WebControls.DropDownList ddlMovies;

        protected global::System.Web.UI.WebControls.DropDownList ddlHalls;

        protected global::System.Web.UI.WebControls.TextBox txtShowName;

        protected global::System.Web.UI.WebControls.TextBox txtShowDate;

        protected global::System.Web.UI.WebControls.TextBox txtShowTime;

        protected global::System.Web.UI.WebControls.Button btnAddShow;

        protected global::System.Web.UI.WebControls.Button btnUpdateShow;

        protected global::System.Web.UI.WebControls.Button btnDeleteShow;

        protected global::System.Web.UI.WebControls.GridView GridViewShows;

        protected global::System.Web.UI.WebControls.DropDownList ddlBookingUsers;

        protected global::System.Web.UI.WebControls.DropDownList ddlBookingShows;

        protected global::System.Web.UI.WebControls.TextBox txtSeatNumber;

        protected global::System.Web.UI.WebControls.TextBox txtTicketPrice;

        protected global::System.Web.UI.WebControls.Button btnBookTicket;

        protected global::System.Web.UI.WebControls.Button btnCancelTicket;

        protected global::System.Web.UI.WebControls.GridView GridViewTickets;
    }
}
