//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23049999_Sewanta_Luitel
{


    public partial class _Default
    {
        protected global::System.Web.UI.WebControls.HyperLink lnkDashboard;
    }
}
