//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _23049999_Sewanta_Luitel
{


    public partial class Report
    {

        protected global::System.Web.UI.WebControls.DropDownList ddlReportUsers;

        protected global::System.Web.UI.WebControls.Button btnSearchReport;

        protected global::System.Web.UI.WebControls.GridView GridViewReport;

        protected global::System.Web.UI.WebControls.DropDownList ddlMovieOccupancy;

        protected global::System.Web.UI.WebControls.Button btnSearchOccupancy;

        protected global::System.Web.UI.WebControls.GridView GridViewOccupancy;

        protected global::System.Web.UI.WebControls.DropDownList ddlHallReport;

        protected global::System.Web.UI.WebControls.Button btnSearchHallReport;

        protected global::System.Web.UI.WebControls.GridView GridViewHallReport;
    }
}
